module FMOD
  module Core
    module ChannelMask
      FRONT_LEFT = 0x00000001
      FRONT_RIGHT = 0x00000002
      FRONT_CENTER = 0x00000004
      LOW_FREQUENCY = 0x00000008
      SURROUND_LEFT = 0x00000010
      SURROUND_RIGHT = 0x00000020
      BACK_LEFT = 0x00000040
      BACK_RIGHT = 0x00000080
      BACK_CENTER = 0x00000100
      MONO = FRONT_LEFT
      STEREO = FRONT_LEFT | FRONT_RIGHT
      LRC = FRONT_LEFT | FRONT_RIGHT | FRONT_CENTER
      QUAD = FRONT_LEFT | FRONT_RIGHT | SURROUND_LEFT | SURROUND_RIGHT
      SURROUND = FRONT_LEFT | FRONT_RIGHT | FRONT_CENTER | SURROUND_LEFT | SURROUND_RIGHT
      FIVE_POINT_ONE = FRONT_LEFT | FRONT_RIGHT | FRONT_CENTER | LOW_FREQUENCY | SURROUND_LEFT | SURROUND_RIGHT
      FIVE_POINT_ONE_REARS = FRONT_LEFT | FRONT_RIGHT | FRONT_CENTER | LOW_FREQUENCY | BACK_LEFT | BACK_RIGHT
      SEVEN_POINT_ZERO = FRONT_LEFT | FRONT_RIGHT | FRONT_CENTER | SURROUND_LEFT | SURROUND_RIGHT | BACK_LEFT | BACK_RIGHT
      SEVEN_POINT_ONE = FRONT_LEFT | FRONT_RIGHT | FRONT_CENTER | LOW_FREQUENCY | SURROUND_LEFT | SURROUND_RIGHT | BACK_LEFT | BACK_RIGHT
    end
  end
end